# Generated by Django 5.2.7 on 2025-10-20 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('skill_level', models.CharField(choices=[('unskilled', 'Unskilled'), ('semi_skilled', 'Semi-Skilled'), ('skilled', 'Skilled'), ('professional', 'Professional')], default='skilled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Labor Categories',
                'db_table': 'labor_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(choices=[('001', 'Mombasa'), ('002', 'Kwale'), ('003', 'Kilifi'), ('004', 'Tana River'), ('005', 'Lamu'), ('006', 'Taita-Taveta'), ('007', 'Garissa'), ('008', 'Wajir'), ('009', 'Mandera'), ('010', 'Marsabit'), ('011', 'Isiolo'), ('012', 'Meru'), ('013', 'Tharaka-Nithi'), ('014', 'Embu'), ('015', 'Kitui'), ('016', 'Machakos'), ('017', 'Makueni'), ('018', 'Nyandarua'), ('019', 'Nyeri'), ('020', 'Kirinyaga'), ('021', "Murang'a"), ('022', 'Kiambu'), ('023', 'Turkana'), ('024', 'West Pokot'), ('025', 'Samburu'), ('026', 'Trans-Nzoia'), ('027', 'Uasin Gishu'), ('028', 'Elgeyo-Marakwet'), ('029', 'Nandi'), ('030', 'Baringo'), ('031', 'Laikipia'), ('032', 'Nakuru'), ('033', 'Narok'), ('034', 'Kajiado'), ('035', 'Kericho'), ('036', 'Bomet'), ('037', 'Kakamega'), ('038', 'Vihiga'), ('039', 'Bungoma'), ('040', 'Busia'), ('041', 'Siaya'), ('042', 'Kisumu'), ('043', 'Homa Bay'), ('044', 'Migori'), ('045', 'Kisii'), ('046', 'Nyamira'), ('047', 'Nairobi')], default='047', max_length=3, unique=True)),
                ('county_name', models.CharField(default='Nairobi', max_length=100)),
                ('region', models.CharField(default='Central', help_text='Region (e.g., Central, Rift Valley, Western, etc.)', max_length=50)),
                ('major_towns', models.TextField(blank=True, help_text='Comma-separated list of major towns in the county')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cost_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for cost adjustment (1.00 = base price, 1.2 = 20% more expensive)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'locations',
                'ordering': ['county_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
                'db_table': 'material_categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_cost_per_sqm', models.DecimalField(decimal_places=2, help_text='Base cost per square meter in KES', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('m', 'Meter'), ('m2', 'Square Meter'), ('m3', 'Cubic Meter'), ('piece', 'Piece'), ('bag', 'Bag'), ('ton', 'Ton'), ('litre', 'Litre')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.materialcategory')),
            ],
            options={
                'db_table': 'materials',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('specifications', models.JSONField(default=dict, help_text='JSON field containing material quantities and specifications')),
                ('estimated_duration_days', models.IntegerField(blank=True, help_text='Estimated project duration in days', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='projects.projecttype')),
            ],
            options={
                'db_table': 'project_templates',
                'ordering': ['project_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LaborPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rate in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='projects.laborcategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_prices', to='projects.location')),
            ],
            options={
                'db_table': 'labor_prices',
                'indexes': [models.Index(fields=['category', 'location'], name='labor_price_categor_24dfcc_idx'), models.Index(fields=['is_active', 'last_updated'], name='labor_price_is_acti_07373c_idx')],
                'unique_together': {('category', 'location')},
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prices', to='projects.location')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='projects.material')),
            ],
            options={
                'db_table': 'material_prices',
                'indexes': [models.Index(fields=['material', 'location'], name='material_pr_materia_13c2e5_idx'), models.Index(fields=['is_active', 'last_updated'], name='material_pr_is_acti_8b85d3_idx')],
                'unique_together': {('material', 'location')},
            },
        ),
    ]
