# Generated by Django 5.2.7 on 2025-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename if created via upload', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='source',
            field=models.CharField(default='manual', help_text='How this estimate was created: manual or upload', max_length=20),
        ),
    ]
