# Generated by Django 5.2.7 on 2025-10-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_add_estimation_fields'),
        ('estimates', '0002_estimate_original_filename_estimate_source'),
    ]

    operations = [
    ]
