# Generated by Django 5.2.7 on 2025-10-29 23:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_merge_20251028_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('location_multiplier', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('adjusted_cost_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('materials_breakdown', models.JSONField(help_text='Detailed breakdown of material costs and quantities')),
                ('labor_breakdown', models.JSONField(help_text='Detailed breakdown of labor costs and hours')),
                ('equipment_details', models.JSONField(help_text='Equipment requirements and associated costs')),
                ('recommendations', models.JSONField(help_text='AI-generated recommendations for cost optimization')),
                ('risk_factors', models.JSONField(help_text='Identified risk factors that may impact costs')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence score for the estimate (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sustainability_metrics', models.JSONField(blank=True, help_text='Environmental impact and sustainability considerations', null=True)),
                ('timeline_impact', models.JSONField(blank=True, help_text='Estimated timeline impacts of different choices', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_estimate', to='estimates.estimate')),
            ],
            options={
                'db_table': 'ai_estimates',
                'ordering': ['-created_at'],
            },
        ),
    ]
