# Generated by Django 5.2.7 on 2025-11-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_aiestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='data_period',
            field=models.CharField(choices=[('Q1', 'Q1 (Quarter 1)'), ('Q2', 'Q2 (Quarter 2)'), ('Q3', 'Q3 (Quarter 3)'), ('Q4', 'Q4 (Quarter 4)'), ('3months', '3 Months'), ('6months', '6 Months'), ('9months', '9 Months'), ('12months', '12 Months')], default='Q1', max_length=10),
        ),
    ]
