# Generated by Django 5.2.7 on 2025-11-04 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_alter_estimate_data_period'),
        ('projects', '0002_alter_location_county_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='file_path',
            field=models.CharField(blank=True, help_text='Storage path for uploaded file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='adjusted_cost_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='base_cost_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.location'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.projecttype'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
