# Generated by Django 5.2.7 on 2025-11-10 01:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0006_estimate_file_path_estimate_processing_completed_at_and_more'),
        ('projects', '0002_alter_location_county_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(help_text='Complete raw response from AI model')),
                ('model_version', models.CharField(help_text='AI model used for generation (e.g., gemini-2.0-flash-exp)', max_length=100)),
                ('labor_roles', models.JSONField(help_text='List of labor roles with details (role, skill level, workers, duration, rates, costs)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal of all labor costs before deductions', max_digits=15)),
                ('statutory_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Statutory deductions and benefits (NSSF, NHIF, etc.)', max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total labor cost including deductions', max_digits=15)),
                ('recommendations', models.JSONField(default=list, help_text='AI-generated recommendations for workforce optimization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Labor Estimate',
                'verbose_name_plural': 'Labor Estimates',
                'db_table': 'labor_estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiestimate',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Estimate', 'verbose_name_plural': 'AI Estimates'},
        ),
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estimate', 'verbose_name_plural': 'Estimates'},
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Estimate Item', 'verbose_name_plural': 'Estimate Items'},
        ),
        migrations.AlterModelOptions(
            name='estimaterevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estimate Revision', 'verbose_name_plural': 'Estimate Revisions'},
        ),
        migrations.AlterModelOptions(
            name='estimateshare',
            options={'ordering': ['-created_at'], 'verbose_name': 'Estimate Share', 'verbose_name_plural': 'Estimate Shares'},
        ),
        migrations.AlterField(
            model_name='aiestimate',
            name='adjusted_cost_per_sqm',
            field=models.DecimalField(decimal_places=2, help_text='Adjusted cost per square meter', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='aiestimate',
            name='base_cost_per_sqm',
            field=models.DecimalField(decimal_places=2, help_text='Base cost per square meter', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='aiestimate',
            name='estimate',
            field=models.OneToOneField(help_text='Parent estimate record', on_delete=django.db.models.deletion.CASCADE, related_name='ai_estimate', to='estimates.estimate'),
        ),
        migrations.AlterField(
            model_name='aiestimate',
            name='location_multiplier',
            field=models.DecimalField(decimal_places=2, help_text='Location adjustment factor', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='adjusted_cost_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base cost adjusted for location', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='base_cost_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base construction cost per square meter', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='building_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure'), ('industrial', 'Industrial')], help_text='Category of building', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='construction_type',
            field=models.CharField(choices=[('new_construction', 'New Construction'), ('repair', 'Repair')], default='new_construction', help_text='Type of construction work', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='contingency_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated contingency amount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='data_period',
            field=models.CharField(choices=[('Q1', 'Q1 (Quarter 1)'), ('Q2', 'Q2 (Quarter 2)'), ('Q3', 'Q3 (Quarter 3)'), ('Q4', 'Q4 (Quarter 4)'), ('3months', '3 Months'), ('6months', '6 Months'), ('9months', '9 Months'), ('12months', '12 Months')], default='Q1', help_text='Time period for cost data', max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this estimate is publicly visible'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Geographic location of the project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.location'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='location_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Location-based cost adjustment multiplier', max_digits=5),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, help_text='When async processing completed', null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='When async processing started', null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_description',
            field=models.TextField(blank=True, help_text='Brief description of the project (max 150 characters)', max_length=150),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_name',
            field=models.CharField(help_text='Name of the construction project', max_length=200),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_template',
            field=models.ForeignKey(blank=True, help_text='Template used for this estimate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttemplate'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Type of project (e.g., Residential, Commercial)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.projecttype'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='source',
            field=models.CharField(default='manual', help_text='How this estimate was created: manual, upload, or ai', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='draft', help_text='Current status of the estimate', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total project area in square meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='total_estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total estimated project cost', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(help_text='User who created this estimate', on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='category',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('overhead', 'Overhead'), ('other', 'Other')], help_text='Item category', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the item'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='estimate',
            field=models.ForeignKey(help_text='Parent estimate', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimate'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='name',
            field=models.CharField(help_text='Item name or description', max_length=200),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or specifications'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity required', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit price)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit',
            field=models.CharField(help_text='Unit of measurement (e.g., kg, m², hours)', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='changes_summary',
            field=models.TextField(help_text='Summary of changes made in this revision'),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this revision', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='estimate',
            field=models.ForeignKey(help_text='Estimate being revised', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='estimates.estimate'),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='new_total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost after this revision', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='previous_total_cost',
            field=models.DecimalField(decimal_places=2, help_text='Total cost before this revision', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimaterevision',
            name='revision_number',
            field=models.PositiveIntegerField(help_text='Sequential revision number'),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='access_token',
            field=models.CharField(help_text='Unique token for accessing shared estimate', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this share', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='estimate',
            field=models.ForeignKey(help_text='Estimate being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='estimates.estimate'),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='expires_at',
            field=models.DateTimeField(help_text='When this share link expires'),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this share link is active'),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='shared_with_email',
            field=models.EmailField(help_text='Email address of recipient', max_length=254),
        ),
        migrations.AlterField(
            model_name='estimateshare',
            name='shared_with_name',
            field=models.CharField(blank=True, help_text='Name of recipient', max_length=200),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['user', '-created_at'], name='estimates_user_id_9219f6_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['status', '-created_at'], name='estimates_status_81d9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['project_type', '-created_at'], name='estimates_project_36822a_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['estimate', 'category'], name='estimate_it_estimat_798d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='estimaterevision',
            index=models.Index(fields=['estimate', '-revision_number'], name='estimate_re_estimat_7b2f92_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateshare',
            index=models.Index(fields=['access_token'], name='estimate_sh_access__6fe195_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateshare',
            index=models.Index(fields=['estimate', '-created_at'], name='estimate_sh_estimat_8a546c_idx'),
        ),
        migrations.AddField(
            model_name='laborestimate',
            name='estimate',
            field=models.OneToOneField(help_text='Parent estimate record', on_delete=django.db.models.deletion.CASCADE, related_name='labor_estimate', to='estimates.estimate'),
        ),
        migrations.AddIndex(
            model_name='laborestimate',
            index=models.Index(fields=['estimate'], name='labor_estim_estimat_38429e_idx'),
        ),
        migrations.AddIndex(
            model_name='laborestimate',
            index=models.Index(fields=['-created_at'], name='labor_estim_created_606eeb_idx'),
        ),
    ]
